require_relative 'config/environment'

# Rakefile == Ruby Makefile
# Makefile, a file where you build 
# bash commands for commonly repeated
# tasks (updating a file similarly over time, etc.)

desc 'Loads up a console!'
task :console do
  Pry.start
end

desc 'Generates hipster gibberish.'
task :hipster_words do
  puts Faker::Hipster.sentence
end